apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-charts.fullname" . }}
  labels: 
    {{- include "custom-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.defaultPort }}
      targetPort: http  
      protocol: TCP
      name: http